name: get_data_from_iss

# Schedule the run
on:
  workflow_dispatch:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  # Set the job key.
  scrape-data:
    # Name of the Job
    name: Scrape data
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Check out a copy of this repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Get data
      - name: Get data
        run: ./get_data.sh

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Parse them all
      - name: Parse them all
        run: |
          python parser.py

      # Commit & Push
      - name: Commit a new report (if necessary)
        run: |
          echo "Checking data on: `date`"
          if [ -n "$(git status --porcelain)" ]; then
            echo "New update available"
            report_date=$(cat data/latest/date)
            mkdir data/${report_date}
            cp data/latest/* data/${report_date}
            git config --global user.name 'GitHub Actions'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add .
            git commit -am "Add new report (${report_date})"
            git push
          else
            echo "no changes to commit"
          fi
        env:
          TZ: Europe/Rome
